version: '3.1'

services:
  app:
    build: .
    container_name: ${APP_NAME}_API
    ports:
      - 2302:2302
    networks:
      - app
    env_file:
      - .env
    volumes:
      - .:/app/
      - /app/build
      - /app/node_modules
    restart: always

  # db:
  #   image: postgres:11.5
  #   container_name: ${APP_NAME}_DB
  #   env_file:
  #     - .env
  #   environment:
  #     POSTGRES_PASSWORD: "${DB_PASSWORD}"
  #     POSTGRES_USER: "${DB_USER}"
  #     POSTGRES_DB: "${DB_NAME}"
  #   networks:
  #     - app
  #   ports:
  #     - 5431:5432
  #   restart: always

  # adminer:
  #   image: adminer
  #   container_name: ${APP_NAME}_ADMIN
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   env_file:
  #     - .env
  #   networks:
  #     - app

networks:
  app:
    driver: bridge